### ISSUE TITLE
No noise reinjection?

### ISSUE THREAD

**Issue by rayray9999** [HavenFeng/time_reversal#1]
Hello,
Thank you for your great work! it has been incredibly beneficial.
However, I noticed that the `pipeline_stable_video_diffusion_re.py` script does not include noise reinjection, 
which is the crucial part of the algorithm. Do I miss something?
<img width="521" alt="截圖 2024-10-06 中午12 47 09" src="https://github.com/user-attachments/assets/d5585ff5-9465-470a-837f-b10c4c239601">

**Comment by HavenFeng** [comment]
Here it is, in a different file: https://github.com/HavenFeng/time_reversal/blob/dcd12db89e0e2e5ba059ad66432adade07687dce/scheduling_euler_discrete_resampling.py#L472
